### ISSUE TITLE
style: misalignment of not h-tag targets

### ISSUE THREAD

**Issue by FabianBartl** [FabianBartl/mtex-toolbox#25]
Bisher:

```css
/* icon after link, actually after last letter of link to prevent breaking  */
abbr[title]:after,
:hover > .anchorjs-link:after,
:target:before,
a:after {
    font-family: "FontAwesome";
    font-weight: normal;
    font-style: normal;
    display: inline-block;
    text-decoration: none;
    padding-left: 3px;
}
```

```css
/* anchor icon before target element */
:target:before {
    width: 0;
    margin: 0;
    padding: 0;
    transform: scale(0.5) translate(-1.1em, 10%);
    content: "\f13d"; /* anchor */
}
```
